### ISSUE TITLE
Why `identifier()` method result in Query and Talker sentence contains trailing comma?

### ISSUE THREAD

**Issue by navado** [Knio/pynmea2#119]
This makes the identifier field confusing and makes message reconstruction less straight forward

**Comment by Knio** [comment]
A handful of proprietary talkers violate the protocol and do not contain a comma. In order to support those protocols and be useful, the comma has to be explicitly managed here.

Can you show a concrete example of what you mean by "message reconstruction less straight forward" and what you would like to see instead?
