### ISSUE TITLE
Live stream example

### ISSUE THREAD

**Issue by joabakk** [Knio/pynmea2#31]
Hi,

Would you be able to add an example of  a script streaming and parsing a live feed from a pty or serial interface? I guess that is something many would use pynmea2 for. Excellent work by the way

**Comment by Knio** [comment]
The NMEAStreamReader class will read from a file-like device and return NMEA messages. I have added a small example here: https://github.com/Knio/pynmea2/blob/master/examples/serial.py

However, I'm afraid this won't really answer people's questions with serial devices, because so much of the code for those are to handle weird things like buffering, like endings, timeouts, connecting/initializing, and IO errors, all of which can be very specific to the individual device or OS/library you're using to connect. I also have minimal experience with real hardware devices myself, and so can only show what worked for my one device, and so have tried to keep pynmea2 closer to the pure software side of things. 

If you do have any examples yourself, or think NMEAStreamReader should have some different behavior or options, it would be useful to add.
