### ISSUE TITLE
The `identifier` method returns sentence name with coma

### ISSUE THREAD

**Issue by wrobell** [Knio/pynmea2#61]
The `identifier` method returns sentence name with coma.

The script
```
import pynmea2

s = '$GPGSV,2,1,08,01,40,083,46,02,17,308,41,12,07,344,39,14,22,228,45*75'
item = pynmea2.parse(s)
print(item.identifier())
```
outputs
```
GPGSV,
```
I would expect
```
GPGSV
```

**Comment by Knio** [comment]
This is the expected behavior.

Instead, (for standard talker types) you can use `item.talker` and `item.sentence_type`:
```python
>>> item.talker
'GP'
>>> item.sentence_type
'GSV'
```

The reasoning for this is that some proprietary NMEA extensions do not correctly include the comma after the message type and instead directly append the message data, so unfortunately the comma then becomes a significant factor in correctly determining the message type.
